import Head from "next/head";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import { Typography } from "@mui/material";
import CachedIcon from "@mui/icons-material/Cached";

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>Employee Leave Manager App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Button
          variant="contained"
          color="secondary"
          startIcon={<CachedIcon />}
        >
          Làm mới
        </Button>
        <Typography variant="h1">abc</Typography>
      </Box>
    </>
  );
}
