export const hotelData = {
  id: 10,
  name: "The Empyrean Nha Trang",
  address: "2, Nguyễn Thị Minh Khai, Thành Phố Nha Trang, Khánh Hòa",
  location: "Uua9D5ba",
  description: "Modern hotel with city views.",
  contact: "0123456789",
  serviceCharge: 888888,
  created_at: "2024-03-06T06:21:22.643Z",
  updated_at: "2024-03-22T14:47:46.034Z",
  images: [
    {
      id: 45,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
      caption: "Caption for image 1",
      is_primary: false,
    },
    {
      id: 46,
      url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
      caption: "Caption for image 2",
      is_primary: false,
    },
    {
      id: 47,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
      caption: "Caption for image 3",
      is_primary: true,
    },
    {
      id: 48,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
      caption: "Caption for image 4",
      is_primary: false,
    },
    {
      id: 49,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
      caption: "Caption for image 5",
      is_primary: false,
    },
  ],
  roomList: [
    {
      id: 64,
      number: "Deluxe King (Khu Khách Sạn)",
      type: "single",
      price: 600000,
      discount: 100000,
      capacity: 2,
      description: "A cozy single room with a view.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 65,
      number: "Deluxe Twin (Khu Căn Hộ hoặc Khu Khách Sạn)",
      type: "double",
      price: 700000,
      discount: 150000,
      capacity: 3,
      description: "Spacious double room with twin beds.",
      rating_average: "0.0",
      status: "unavailable",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 66,
      number: "103",
      type: "suite",
      price: 800000,
      discount: 200000,
      capacity: 4,
      description: "Luxurious suite with a living area.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 67,
      number: "104",
      type: "single",
      price: 550000,
      discount: 80000,
      capacity: 2,
      description: "Compact single room with modern amenities.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 68,
      number: "105",
      type: "double",
      price: 650000,
      discount: 120000,
      capacity: 3,
      description: "Double room with a balcony overlooking the city.",
      rating_average: "0.0",
      status: "unavailable",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 69,
      number: "106",
      type: "suite",
      price: 750000,
      discount: 180000,
      capacity: 4,
      description: "Elegant suite with separate living and sleeping areas.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 70,
      number: "107",
      type: "single",
      price: 580000,
      discount: 90000,
      capacity: 2,
      description: "Comfortable single room with a work desk.",
      rating_average: "0.0",
      status: "unavailable",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 71,
      number: "108",
      type: "double",
      price: 680000,
      discount: 130000,
      capacity: 3,
      description: "Modern double room with city views.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 72,
      number: "109",
      type: "suite",
      price: 780000,
      discount: 190000,
      capacity: 4,
      description: "Spacious suite with luxurious amenities.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 73,
      number: "110",
      type: "single",
      price: 570000,
      discount: 85000,
      capacity: 2,
      description: "Cozy single room with a comfortable bed.",
      rating_average: "0.0",
      status: "unavailable",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    {
      id: 81,
      number: "601",
      type: "Penthouse",
      price: 5000000,
      discount: 900000,
      capacity: 2,
      description: "Luxurious penthouse suite",
      rating_average: "5.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
  ],
};

export const amenitiesData = [
  {
    id: 1,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 2,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 3,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 4,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 5,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 6,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 7,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 8,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
];

export const ratingData = [
  {
    id: 1,
    criteria: "Vị trí",
    rating: "8.4",
  },
  {
    id: 2,
    criteria: "Giá cả",
    rating: "8.6",
  },
  {
    id: 3,
    criteria: "Phục vụ",
    rating: "8.5",
  },
  {
    id: 4,
    criteria: "Vệ sinh",
    rating: "8.0",
  },
  {
    id: 5,
    criteria: "Tiện nghi",
    rating: "9.2",
  },
];

export const filterRoom = [
  "Không hút thuốc",
  "Có ăn sáng",
  "Lựa chọn trả tiền sau",
  "Hủy miễn phí",
  "Nhà bếp",
  "Giường đôi lớn",
  "Giường lớn",
  "Hai giường",
  "Hướng núi",
];

export const roomAmenities = [
  "Điều hòa nhiệt độ",
  "Khăn tắm",
  "Cửa sổ",
  "Không hút thuốc",
  "Đồ vệ sinh cá nhân miễn phí",
  "Tivi màn hình phẳng",
  "Phòng tắm riêng",
  "Bình nước nóng",
  "Wifi miễn phí",
  "Bàn làm việc",
  "Vòi hoa sen",
  "Tủ",
  "Trà, cà phê miễn phí",
  "Nước suối miễn phí",
  "Dọn phòng hàng ngày",
  "Ấm đun nước điện",
  "Kệ để hành lý",
  "Tủ quần áo",
  "Máy sấy tóc",
  "Giá treo quần áo",
];

export const roomBenefits = [
  "Hoàn huỷ một phần",
  "Giá đã bao gồm bữa sáng",
  "Chính sách đặt phòng & phụ thu",
  "Xác nhận trong 15 phút",
  "An tâm đặt phòng, Mytour hỗ trợ xuất hoá đơn nhanh chóng, tiết kiệm thời gian cho bạn.",
];
