export const hotelData = {
  id: 10,
  name: "The Empyrean Nha Trang",
  address: "2, Nguyễn Thị Minh Khai, Thành Phố Nha Trang, Khánh Hòa",
  location: "Uua9D5ba",
  description: "Modern hotel with city views.",
  contact: "0123456789",
  serviceCharge: 888888,
  created_at: "2024-03-06T06:21:22.643Z",
  updated_at: "2024-03-22T14:47:46.034Z",
  images: [
    {
      id: 45,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
      caption: "Caption for image 1",
      is_primary: false,
    },
    {
      id: 46,
      url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
      caption: "Caption for image 2",
      is_primary: false,
    },
    {
      id: 47,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
      caption: "Caption for image 3",
      is_primary: true,
    },
    {
      id: 48,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
      caption: "Caption for image 4",
      is_primary: false,
    },
    {
      id: 49,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
      caption: "Caption for image 5",
      is_primary: false,
    },
  ],
  roomList: [
    {
      id: 64,
      number: "Deluxe King (Khu Khách Sạn)",
      type: "single",
      price: 600000,
      discount: 100000,
      capacity: 2,
      description: "A cozy single room with a view.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    // {
    //   id: 65,
    //   number: "Deluxe Twin (Khu Căn Hộ hoặc Khu Khách Sạn)",
    //   type: "double",
    //   price: 700000,
    //   discount: 150000,
    //   capacity: 3,
    //   description: "Spacious double room with twin beds.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 66,
    //   number: "103",
    //   type: "suite",
    //   price: 800000,
    //   discount: 200000,
    //   capacity: 4,
    //   description: "Luxurious suite with a living area.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 67,
    //   number: "104",
    //   type: "single",
    //   price: 550000,
    //   discount: 80000,
    //   capacity: 2,
    //   description: "Compact single room with modern amenities.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 68,
    //   number: "105",
    //   type: "double",
    //   price: 650000,
    //   discount: 120000,
    //   capacity: 3,
    //   description: "Double room with a balcony overlooking the city.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 69,
    //   number: "106",
    //   type: "suite",
    //   price: 750000,
    //   discount: 180000,
    //   capacity: 4,
    //   description: "Elegant suite with separate living and sleeping areas.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 70,
    //   number: "107",
    //   type: "single",
    //   price: 580000,
    //   discount: 90000,
    //   capacity: 2,
    //   description: "Comfortable single room with a work desk.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 71,
    //   number: "108",
    //   type: "double",
    //   price: 680000,
    //   discount: 130000,
    //   capacity: 3,
    //   description: "Modern double room with city views.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 72,
    //   number: "109",
    //   type: "suite",
    //   price: 780000,
    //   discount: 190000,
    //   capacity: 4,
    //   description: "Spacious suite with luxurious amenities.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 73,
    //   number: "110",
    //   type: "single",
    //   price: 570000,
    //   discount: 85000,
    //   capacity: 2,
    //   description: "Cozy single room with a comfortable bed.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 81,
    //   number: "601",
    //   type: "Penthouse",
    //   price: 5000000,
    //   discount: 900000,
    //   capacity: 2,
    //   description: "Luxurious penthouse suite",
    //   rating_average: "5.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
  ],
  reviews: [
    {
      id: 479232,
      username: "Trần Hải",
      avatar: null,
      title: "Điểm tối đa",
      content:
        "Tôi rất hài lòng khi nghỉ ngơi tại Swiss-Belresort Tuyen Lam Dalat Resort dù ở đây hơi xa trung tâm nhưng các dịch vụ resort cung cấp rất tốt. Từ chất lượng phòng cũng như thái độ phục vụ của nhân viên. ",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: {
        content:
          "Kính gửi Thương,\nMường Thanh Luxury Saigon Hotel gửi lời chào đến chị. Chân thành cám ơn những đóng góp từ chị, đây sẽ là động lực giúp khách sạn cố gắng phát huy và phục vụ ngày một tốt hơn.\nTrân trọng,\nĐinh Thọ Quang - GM",
        createdAt: 1700185279000,
        images: null,
      },
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-01-04 15:52:47",
      publishedDate: "2018-01-04 08:52:47",
      images: [],
      hotelName: null,
    },
    {
      id: 388096,
      username: "Thi",
      avatar: null,
      title: "Quá Tuyệt",
      content:
        "Tôi đã có 1 kỳ nghỉ tuyệt vời ở đây! Nhân viên vô cùng tốt bụng và thân thiện. Trong khi dùng bữa tối tại đây, tôi có nói chuyện với chồng là tôi bị mệt...Ngay sau đó tôi đc quản lý tại nhà hàng hỏi han và mời tôi dùng trà gừng và cháo (sau đó họ ko tính phí). Tôi rất cảm động vì điều đó! Khung cảnh nơi đây vô cùng tuyệt vời! ",
      travelType: "Khác",
      rating: 8.8,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-04-21 00:00:00",
      publishedDate: "2018-04-20 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 479233,
      username: "Cường",
      avatar: null,
      title: "Resort 5 sao",
      content:
        "Xứng đáng là 5 sao chỉ là ks ở hơi xa trung tâm và ko được nhận phòng sớm",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-07-31 08:15:07",
      publishedDate: "2020-07-31 01:15:07",
      images: [],
      hotelName: null,
    },
    {
      id: 453377,
      username: null,
      avatar: null,
      title: "Tuyệt vời!!",
      content:
        "Đây là lần thứ 2 tôi nghỉ dưỡng tại Swiss-bel Tuyền Lâm, lần này tôi đã book được phòng view golf, khung cảnh lãng mạng vào những buổi sáng sớm. Sương mù lơ lửng cùng với cái lạnh ĐL thật sảng khoái và thơ mộng. Ở đây có đầy đủ dịch vụ, có Spa- massage theo phong cách người Hàn rất thích. Đặc biệt là chúng tôi ấn tượng nhất ở chị Amanda, chị đã hướng dẫn và giới thiệu các dịch vụ của khách sạn. Sau đó chị đã book cho chúng tôi 1 xe điện để đi tham quan sân Golf. Thật tuyệt vời. Cám ơn khách sạn và cám ơn chị Amanda. Chúng tôi sẽ quay lại đây.",
      travelType: "Khác",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2019-02-16 00:00:00",
      publishedDate: "2019-02-15 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 479234,
      username: "Huyền",
      avatar: null,
      title: "Tốt",
      content:
        "khách sạn đẹp, nhân viên nhiệt tình, sạch sẽ, thân thiện, phù hợp giá tiền",
      travelType: "Du lịch một mình",
      rating: 6.2,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-08-26 09:15:11",
      publishedDate: "2020-08-26 02:15:11",
      images: [],
      hotelName: null,
    },
    {
      id: 470454,
      username: "Trần Hải",
      avatar: null,
      title: "Điểm tối đa",
      content:
        "Tôi rất hài lòng khi nghỉ ngơi tại Swiss-Belresort Tuyen Lam Dalat Resort dù ở đây hơi xa trung tâm nhưng các dịch vụ resort cung cấp rất tốt. Từ chất lượng phòng cũng như thái độ phục vụ của nhân viên. ",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: {
        content:
          "Kính gửi Thương,\nMường Thanh Luxury Saigon Hotel gửi lời chào đến chị. Chân thành cám ơn những đóng góp từ chị, đây sẽ là động lực giúp khách sạn cố gắng phát huy và phục vụ ngày một tốt hơn.\nTrân trọng,\nĐinh Thọ Quang - GM",
        createdAt: 1700185279000,
        images: null,
      },
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-01-04 15:52:47",
      publishedDate: "2018-01-04 08:52:47",
      images: [],
      hotelName: null,
    },
    {
      id: 1,
      username: "Thi",
      avatar: null,
      title: "Quá Tuyệt",
      content:
        "Tôi đã có 1 kỳ nghỉ tuyệt vời ở đây! Nhân viên vô cùng tốt bụng và thân thiện. Trong khi dùng bữa tối tại đây, tôi có nói chuyện với chồng là tôi bị mệt...Ngay sau đó tôi đc quản lý tại nhà hàng hỏi han và mời tôi dùng trà gừng và cháo (sau đó họ ko tính phí). Tôi rất cảm động vì điều đó! Khung cảnh nơi đây vô cùng tuyệt vời! ",
      travelType: "Khác",
      rating: 8.8,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-04-21 00:00:00",
      publishedDate: "2018-04-20 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 2,
      username: "Cường",
      avatar: null,
      title: "Resort 5 sao",
      content:
        "Xứng đáng là 5 sao chỉ là ks ở hơi xa trung tâm và ko được nhận phòng sớm",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-07-31 08:15:07",
      publishedDate: "2020-07-31 01:15:07",
      images: [],
      hotelName: null,
    },
    {
      id: 3,
      username: null,
      avatar: null,
      title: "Tuyệt vời!!",
      content:
        "Đây là lần thứ 2 tôi nghỉ dưỡng tại Swiss-bel Tuyền Lâm, lần này tôi đã book được phòng view golf, khung cảnh lãng mạng vào những buổi sáng sớm. Sương mù lơ lửng cùng với cái lạnh ĐL thật sảng khoái và thơ mộng. Ở đây có đầy đủ dịch vụ, có Spa- massage theo phong cách người Hàn rất thích. Đặc biệt là chúng tôi ấn tượng nhất ở chị Amanda, chị đã hướng dẫn và giới thiệu các dịch vụ của khách sạn. Sau đó chị đã book cho chúng tôi 1 xe điện để đi tham quan sân Golf. Thật tuyệt vời. Cám ơn khách sạn và cám ơn chị Amanda. Chúng tôi sẽ quay lại đây.",
      travelType: "Khác",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2019-02-16 00:00:00",
      publishedDate: "2019-02-15 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 5,
      username: "Huyền",
      avatar: null,
      title: "Tốt",
      content:
        "khách sạn đẹp, nhân viên nhiệt tình, sạch sẽ, thân thiện, phù hợp giá tiền",
      travelType: "Du lịch một mình",
      rating: 6.2,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-08-26 09:15:11",
      publishedDate: "2020-08-26 02:15:11",
      images: [],
      hotelName: null,
    },
    {
      id: 4,
      username: "Huyền",
      avatar: null,
      title: "Tốt",
      content:
        "khách sạn đẹp, nhân viên nhiệt tình, sạch sẽ, thân thiện, phù hợp giá tiền",
      travelType: "Du lịch một mình",
      rating: 6.2,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-08-26 09:15:11",
      publishedDate: "2020-08-26 02:15:11",
      images: [],
      hotelName: null,
    },
  ],
  countByRatingLevel: [
    {
      value: "FANTASTIC",
      name: "Tuyệt vời",
      count: 400,
    },
    {
      value: "VERY_GOOD",
      name: "Rất tốt",
      count: 165,
    },
    {
      value: "SATISFYING",
      name: "Tốt",
      count: 45,
    },
    {
      value: "AVERAGE",
      name: "Trung bình",
      count: 42,
    },
    {
      value: "POOR",
      name: "Kém",
      count: 14,
    },
  ],
  hotelsAround: [
    {
      hotel_id: 3,
      hotel_name: "Khách sạn Sea Pearl Nha Trang",
      hotel_address: "98a, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/3/1712920829212_Y3vmWc9Kt0_download.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112029Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=5bf40b5605676113bdec88e0e4c708bd67f50b21168e4e11a154a738624fb9fa",
      min_room_price: 900000,
      original_room_price: 1000000,
    },
    {
      hotel_id: 4,
      hotel_name: "Khách sạn Grand Gosia Nha Trang",
      hotel_address:
        "10-12 Trần Phú, Vĩnh Nguyên, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/4/1712891146090_TpaQVvzglH_download3.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T030546Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=dba8bdd8e4a657c9074dd02e4dff507321e08ca723ea04aa04331dac158b05c6",
      min_room_price: 1250000,
      original_room_price: 1500000,
    },
    {
      hotel_id: 5,
      hotel_name: "Khách Sạn Lotte Hà Nội",
      hotel_address: "54, Liễu Giai, Quận Ba Đình, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/5/1712920844797_4Wjd8sQ9rK_download1.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112044Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=4806ee7978db11862f639bca6bc36ce50454e5325807b9c57fc7f10b8e1d7ff0",
      min_room_price: 2250000,
      original_room_price: 2500000,
    },
    {
      hotel_id: 6,
      hotel_name: "Khách sạn Pullman Hanoi",
      hotel_address: "54, Liễu Giai, Quận Ba Đình, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/6/1712920855337_Kg6WxBaDeS_download2.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112055Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a5e494d464d8f2e282743cdfed5e6200398119cf9cc6fc64575e98d888ad5f76",
      min_room_price: 1115000,
      original_room_price: 1200000,
    },
    {
      hotel_id: 7,
      hotel_name: "Khách Sạn Mường Thanh Hà Nội Centre",
      hotel_address: "78, Thợ Nhuộm, Quận Hoàn Kiếm, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/7/1712920869279_eSJctZ2ylB_download5.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112109Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=f88696c89513da6753af27cbec0807eeb287f7ca820eae1c8e65aef2fd382027",
      min_room_price: 1600000,
      original_room_price: 1800000,
    },
    {
      hotel_id: 8,
      hotel_name: "Khách sạn Dolce Hanoi Golden Lake",
      hotel_address: "B7 , Giảng Võ, Quận Ba Đình, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/8/1712920909941_mcu7vpohrZ_download5.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112149Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=4d7a98001fc7d250f8f0b26bfd6cfa06ca5033e07a65c45bb6d35aa172e5a74f",
      min_room_price: 2200000,
      original_room_price: 3000000,
    },
    {
      hotel_id: 9,
      hotel_name: "Khách sạn La Vague",
      hotel_address: "Số 8, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/9/1712891127616_Q9woy3sCMD_download5.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T030527Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=2cc11a6b1122f289daec9ace621f0eab7e1721b95ecc1cbbf5a994f699ae3b4d",
      min_room_price: 1480000,
      original_room_price: 1600000,
    },
    {
      hotel_id: 10,
      hotel_name: "The Empyrean Nha Trang",
      hotel_address: "2 , Nguyễn Thị Minh Khai, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/10/1713772294727_9K84YkFRZM_room2.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240422T075134Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=8c0536fa4c5f6cb965ed5455559e8f7ab40efa84fbff790547e8169e2c64f269",
      min_room_price: 470000,
      original_room_price: 550000,
    },
  ],
};

export const amenitiesData = [
  {
    id: 1,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 2,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 3,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 4,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 5,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 6,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 7,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 8,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
];

export const ratingData = [
  {
    id: 1,
    criteria: "Vị trí",
    rating: "8.4",
  },
  {
    id: 2,
    criteria: "Giá cả",
    rating: "8.6",
  },
  {
    id: 3,
    criteria: "Phục vụ",
    rating: "8.5",
  },
  {
    id: 4,
    criteria: "Vệ sinh",
    rating: "8.0",
  },
  {
    id: 5,
    criteria: "Tiện nghi",
    rating: "9.2",
  },
];

export const filterRoom = [
  "Không hút thuốc",
  "Có ăn sáng",
  "Lựa chọn trả tiền sau",
  "Hủy miễn phí",
  "Nhà bếp",
  "Giường đôi lớn",
  "Giường lớn",
  "Hai giường",
  "Hướng núi",
];

export const roomAmenities = [
  "Điều hòa nhiệt độ",
  "Khăn tắm",
  "Cửa sổ",
  "Không hút thuốc",
  "Đồ vệ sinh cá nhân miễn phí",
  "Tivi màn hình phẳng",
  "Phòng tắm riêng",
  "Bình nước nóng",
  "Wifi miễn phí",
  "Bàn làm việc",
  "Vòi hoa sen",
  "Tủ",
  "Trà, cà phê miễn phí",
  "Nước suối miễn phí",
  "Dọn phòng hàng ngày",
  "Ấm đun nước điện",
  "Kệ để hành lý",
  "Tủ quần áo",
  "Máy sấy tóc",
  "Giá treo quần áo",
];

export const roomBenefits = [
  "Hoàn huỷ một phần",
  "Giá đã bao gồm bữa sáng",
  "Chính sách đặt phòng & phụ thu",
  "Xác nhận trong 15 phút",
  "An tâm đặt phòng, Mytour hỗ trợ xuất hoá đơn nhanh chóng, tiết kiệm thời gian cho bạn.",
];

export const sortOptions = [
  {
    code: "newest",
    textDetail: "Mới nhất",
  },
  {
    code: "oldest",
    textDetail: "Cũ nhất",
  },
  {
    code: "lowest_rating",
    textDetail: "Điểm thấp nhất",
  },
  {
    code: "highest_rating",
    textDetail: "Điểm cao nhất",
  },
];
