// import MapComponent from "@/components/map/map";
import Metadata from "@/components/metadata";
import { Typography } from "@mui/material";

export default function Home() {
  const metadata = {
    title: "Booking",
    description: "Generated by create next app",
  };
  return (
    <>
      <Metadata {...metadata} />
      <Typography variant="h2">Home Page</Typography>
      {/* <MapComponent /> */}
    </>
  )
}
