export const hotelData = {
  id: 10,
  name: "The Empyrean Nha Trang",
  address: "2, Nguyễn Thị Minh Khai, Thành Phố Nha Trang, Khánh Hòa",
  location: "Uua9D5ba",
  description: "Modern hotel with city views.",
  contact: "0123456789",
  serviceCharge: 888888,
  created_at: "2024-03-06T06:21:22.643Z",
  updated_at: "2024-03-22T14:47:46.034Z",
  images: [
    {
      id: 45,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
      caption: "Caption for image 1",
      is_primary: false,
    },
    {
      id: 46,
      url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
      caption: "Caption for image 2",
      is_primary: false,
    },
    {
      id: 47,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
      caption: "Caption for image 3",
      is_primary: true,
    },
    {
      id: 48,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
      caption: "Caption for image 4",
      is_primary: false,
    },
    {
      id: 49,
      url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
      caption: "Caption for image 5",
      is_primary: false,
    },
  ],
  roomList: [
    {
      id: 64,
      number: "Deluxe King (Khu Khách Sạn)",
      type: "single",
      price: 600000,
      discount: 100000,
      capacity: 2,
      description: "A cozy single room with a view.",
      rating_average: "0.0",
      status: "available",
      images: [
        {
          id: 45,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
          caption: "Caption for image 1",
          is_primary: false,
        },
        {
          id: 46,
          url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
          caption: "Caption for image 2",
          is_primary: false,
        },
        {
          id: 47,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
          caption: "Caption for image 3",
          is_primary: true,
        },
        {
          id: 48,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
          caption: "Caption for image 4",
          is_primary: false,
        },
        {
          id: 49,
          url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
          caption: "Caption for image 5",
          is_primary: false,
        },
      ],
    },
    // {
    //   id: 65,
    //   number: "Deluxe Twin (Khu Căn Hộ hoặc Khu Khách Sạn)",
    //   type: "double",
    //   price: 700000,
    //   discount: 150000,
    //   capacity: 3,
    //   description: "Spacious double room with twin beds.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 66,
    //   number: "103",
    //   type: "suite",
    //   price: 800000,
    //   discount: 200000,
    //   capacity: 4,
    //   description: "Luxurious suite with a living area.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 67,
    //   number: "104",
    //   type: "single",
    //   price: 550000,
    //   discount: 80000,
    //   capacity: 2,
    //   description: "Compact single room with modern amenities.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 68,
    //   number: "105",
    //   type: "double",
    //   price: 650000,
    //   discount: 120000,
    //   capacity: 3,
    //   description: "Double room with a balcony overlooking the city.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 69,
    //   number: "106",
    //   type: "suite",
    //   price: 750000,
    //   discount: 180000,
    //   capacity: 4,
    //   description: "Elegant suite with separate living and sleeping areas.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 70,
    //   number: "107",
    //   type: "single",
    //   price: 580000,
    //   discount: 90000,
    //   capacity: 2,
    //   description: "Comfortable single room with a work desk.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 71,
    //   number: "108",
    //   type: "double",
    //   price: 680000,
    //   discount: 130000,
    //   capacity: 3,
    //   description: "Modern double room with city views.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 72,
    //   number: "109",
    //   type: "suite",
    //   price: 780000,
    //   discount: 190000,
    //   capacity: 4,
    //   description: "Spacious suite with luxurious amenities.",
    //   rating_average: "0.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 73,
    //   number: "110",
    //   type: "single",
    //   price: 570000,
    //   discount: 85000,
    //   capacity: 2,
    //   description: "Cozy single room with a comfortable bed.",
    //   rating_average: "0.0",
    //   status: "unavailable",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
    // {
    //   id: 81,
    //   number: "601",
    //   type: "Penthouse",
    //   price: 5000000,
    //   discount: 900000,
    //   capacity: 2,
    //   description: "Luxurious penthouse suite",
    //   rating_average: "5.0",
    //   status: "available",
    //   images: [
    //     {
    //       id: 45,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    //       caption: "Caption for image 1",
    //       is_primary: false,
    //     },
    //     {
    //       id: 46,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    //       caption: "Caption for image 2",
    //       is_primary: false,
    //     },
    //     {
    //       id: 47,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    //       caption: "Caption for image 3",
    //       is_primary: true,
    //     },
    //     {
    //       id: 48,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    //       caption: "Caption for image 4",
    //       is_primary: false,
    //     },
    //     {
    //       id: 49,
    //       url: "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    //       caption: "Caption for image 5",
    //       is_primary: false,
    //     },
    //   ],
    // },
  ],
  reviews: [
    {
      id: 479232,
      username: "Trần Hải",
      avatar: null,
      title: "Điểm tối đa",
      content:
        "Tôi rất hài lòng khi nghỉ ngơi tại Swiss-Belresort Tuyen Lam Dalat Resort dù ở đây hơi xa trung tâm nhưng các dịch vụ resort cung cấp rất tốt. Từ chất lượng phòng cũng như thái độ phục vụ của nhân viên. ",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: {
        content:
          "Kính gửi Thương,\nMường Thanh Luxury Saigon Hotel gửi lời chào đến chị. Chân thành cám ơn những đóng góp từ chị, đây sẽ là động lực giúp khách sạn cố gắng phát huy và phục vụ ngày một tốt hơn.\nTrân trọng,\nĐinh Thọ Quang - GM",
        createdAt: 1700185279000,
        images: null,
      },
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-01-04 15:52:47",
      publishedDate: "2018-01-04 08:52:47",
      images: [],
      hotelName: null,
    },
    {
      id: 388096,
      username: "Thi",
      avatar: null,
      title: "Quá Tuyệt",
      content:
        "Tôi đã có 1 kỳ nghỉ tuyệt vời ở đây! Nhân viên vô cùng tốt bụng và thân thiện. Trong khi dùng bữa tối tại đây, tôi có nói chuyện với chồng là tôi bị mệt...Ngay sau đó tôi đc quản lý tại nhà hàng hỏi han và mời tôi dùng trà gừng và cháo (sau đó họ ko tính phí). Tôi rất cảm động vì điều đó! Khung cảnh nơi đây vô cùng tuyệt vời! ",
      travelType: "Khác",
      rating: 8.8,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-04-21 00:00:00",
      publishedDate: "2018-04-20 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 479233,
      username: "Cường",
      avatar: null,
      title: "Resort 5 sao",
      content:
        "Xứng đáng là 5 sao chỉ là ks ở hơi xa trung tâm và ko được nhận phòng sớm",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-07-31 08:15:07",
      publishedDate: "2020-07-31 01:15:07",
      images: [],
      hotelName: null,
    },
    {
      id: 453377,
      username: null,
      avatar: null,
      title: "Tuyệt vời!!",
      content:
        "Đây là lần thứ 2 tôi nghỉ dưỡng tại Swiss-bel Tuyền Lâm, lần này tôi đã book được phòng view golf, khung cảnh lãng mạng vào những buổi sáng sớm. Sương mù lơ lửng cùng với cái lạnh ĐL thật sảng khoái và thơ mộng. Ở đây có đầy đủ dịch vụ, có Spa- massage theo phong cách người Hàn rất thích. Đặc biệt là chúng tôi ấn tượng nhất ở chị Amanda, chị đã hướng dẫn và giới thiệu các dịch vụ của khách sạn. Sau đó chị đã book cho chúng tôi 1 xe điện để đi tham quan sân Golf. Thật tuyệt vời. Cám ơn khách sạn và cám ơn chị Amanda. Chúng tôi sẽ quay lại đây.",
      travelType: "Khác",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2019-02-16 00:00:00",
      publishedDate: "2019-02-15 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 479234,
      username: "Huyền",
      avatar: null,
      title: "Tốt",
      content:
        "khách sạn đẹp, nhân viên nhiệt tình, sạch sẽ, thân thiện, phù hợp giá tiền",
      travelType: "Du lịch một mình",
      rating: 6.2,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-08-26 09:15:11",
      publishedDate: "2020-08-26 02:15:11",
      images: [],
      hotelName: null,
    },
    {
      id: 470454,
      username: "Trần Hải",
      avatar: null,
      title: "Điểm tối đa",
      content:
        "Tôi rất hài lòng khi nghỉ ngơi tại Swiss-Belresort Tuyen Lam Dalat Resort dù ở đây hơi xa trung tâm nhưng các dịch vụ resort cung cấp rất tốt. Từ chất lượng phòng cũng như thái độ phục vụ của nhân viên. ",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: {
        content:
          "Kính gửi Thương,\nMường Thanh Luxury Saigon Hotel gửi lời chào đến chị. Chân thành cám ơn những đóng góp từ chị, đây sẽ là động lực giúp khách sạn cố gắng phát huy và phục vụ ngày một tốt hơn.\nTrân trọng,\nĐinh Thọ Quang - GM",
        createdAt: 1700185279000,
        images: null,
      },
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-01-04 15:52:47",
      publishedDate: "2018-01-04 08:52:47",
      images: [],
      hotelName: null,
    },
    {
      id: 1,
      username: "Thi",
      avatar: null,
      title: "Quá Tuyệt",
      content:
        "Tôi đã có 1 kỳ nghỉ tuyệt vời ở đây! Nhân viên vô cùng tốt bụng và thân thiện. Trong khi dùng bữa tối tại đây, tôi có nói chuyện với chồng là tôi bị mệt...Ngay sau đó tôi đc quản lý tại nhà hàng hỏi han và mời tôi dùng trà gừng và cháo (sau đó họ ko tính phí). Tôi rất cảm động vì điều đó! Khung cảnh nơi đây vô cùng tuyệt vời! ",
      travelType: "Khác",
      rating: 8.8,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2018-04-21 00:00:00",
      publishedDate: "2018-04-20 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 2,
      username: "Cường",
      avatar: null,
      title: "Resort 5 sao",
      content:
        "Xứng đáng là 5 sao chỉ là ks ở hơi xa trung tâm và ko được nhận phòng sớm",
      travelType: "Du lịch một mình",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-07-31 08:15:07",
      publishedDate: "2020-07-31 01:15:07",
      images: [],
      hotelName: null,
    },
    {
      id: 3,
      username: null,
      avatar: null,
      title: "Tuyệt vời!!",
      content:
        "Đây là lần thứ 2 tôi nghỉ dưỡng tại Swiss-bel Tuyền Lâm, lần này tôi đã book được phòng view golf, khung cảnh lãng mạng vào những buổi sáng sớm. Sương mù lơ lửng cùng với cái lạnh ĐL thật sảng khoái và thơ mộng. Ở đây có đầy đủ dịch vụ, có Spa- massage theo phong cách người Hàn rất thích. Đặc biệt là chúng tôi ấn tượng nhất ở chị Amanda, chị đã hướng dẫn và giới thiệu các dịch vụ của khách sạn. Sau đó chị đã book cho chúng tôi 1 xe điện để đi tham quan sân Golf. Thật tuyệt vời. Cám ơn khách sạn và cám ơn chị Amanda. Chúng tôi sẽ quay lại đây.",
      travelType: "Khác",
      rating: 10,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2019-02-16 00:00:00",
      publishedDate: "2019-02-15 17:00:00",
      images: [],
      hotelName: null,
    },
    {
      id: 5,
      username: "Huyền",
      avatar: null,
      title: "Tốt",
      content:
        "khách sạn đẹp, nhân viên nhiệt tình, sạch sẽ, thân thiện, phù hợp giá tiền",
      travelType: "Du lịch một mình",
      rating: 6.2,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-08-26 09:15:11",
      publishedDate: "2020-08-26 02:15:11",
      images: [],
      hotelName: null,
    },
    {
      id: 4,
      username: "Huyền",
      avatar: null,
      title: "Tốt",
      content:
        "khách sạn đẹp, nhân viên nhiệt tình, sạch sẽ, thân thiện, phù hợp giá tiền",
      travelType: "Du lịch một mình",
      rating: 6.2,
      language: "vi",
      url: null,
      numberVotes: 0,
      isVoted: false,
      reply: null,
      roomName: "Phòng Deluxe  2 Giường Đơn Hướng Phố",
      checkIn: null,
      checkOut: null,
      travelDate: "2020-08-26 09:15:11",
      publishedDate: "2020-08-26 02:15:11",
      images: [],
      hotelName: null,
    },
  ],
  countByRatingLevel: [
    {
      value: "FANTASTIC",
      name: "Tuyệt vời",
      count: 400,
    },
    {
      value: "VERY_GOOD",
      name: "Rất tốt",
      count: 165,
    },
    {
      value: "SATISFYING",
      name: "Tốt",
      count: 45,
    },
    {
      value: "AVERAGE",
      name: "Trung bình",
      count: 42,
    },
    {
      value: "POOR",
      name: "Kém",
      count: 14,
    },
  ],
  hotelsAround: [
    {
      hotel_id: 3,
      hotel_name: "Khách sạn Sea Pearl Nha Trang",
      hotel_address: "98a, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/3/1712920829212_Y3vmWc9Kt0_download.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112029Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=5bf40b5605676113bdec88e0e4c708bd67f50b21168e4e11a154a738624fb9fa",
      min_room_price: 900000,
      original_room_price: 1000000,
      is_favorite_hotel: true,
    },
    {
      hotel_id: 4,
      hotel_name: "Khách sạn Grand Gosia Nha Trang",
      hotel_address:
        "10-12 Trần Phú, Vĩnh Nguyên, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/4/1712891146090_TpaQVvzglH_download3.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T030546Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=dba8bdd8e4a657c9074dd02e4dff507321e08ca723ea04aa04331dac158b05c6",
      min_room_price: 1250000,
      original_room_price: 1500000,
      is_favorite_hotel: false,
    },
    {
      hotel_id: 5,
      hotel_name: "Khách Sạn Lotte Hà Nội",
      hotel_address: "54, Liễu Giai, Quận Ba Đình, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/5/1712920844797_4Wjd8sQ9rK_download1.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112044Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=4806ee7978db11862f639bca6bc36ce50454e5325807b9c57fc7f10b8e1d7ff0",
      min_room_price: 2250000,
      original_room_price: 2500000,
      is_favorite_hotel: false,
    },
    {
      hotel_id: 6,
      hotel_name: "Khách sạn Pullman Hanoi",
      hotel_address: "54, Liễu Giai, Quận Ba Đình, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/6/1712920855337_Kg6WxBaDeS_download2.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112055Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a5e494d464d8f2e282743cdfed5e6200398119cf9cc6fc64575e98d888ad5f76",
      min_room_price: 1115000,
      original_room_price: 1200000,
      is_favorite_hotel: false,
    },
    {
      hotel_id: 7,
      hotel_name: "Khách Sạn Mường Thanh Hà Nội Centre",
      hotel_address: "78, Thợ Nhuộm, Quận Hoàn Kiếm, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/7/1712920869279_eSJctZ2ylB_download5.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112109Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=f88696c89513da6753af27cbec0807eeb287f7ca820eae1c8e65aef2fd382027",
      min_room_price: 1600000,
      original_room_price: 1800000,
      is_favorite_hotel: false,
    },
    {
      hotel_id: 8,
      hotel_name: "Khách sạn Dolce Hanoi Golden Lake",
      hotel_address: "B7 , Giảng Võ, Quận Ba Đình, Hà Nội",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/8/1712920909941_mcu7vpohrZ_download5.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T112149Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=4d7a98001fc7d250f8f0b26bfd6cfa06ca5033e07a65c45bb6d35aa172e5a74f",
      min_room_price: 2200000,
      original_room_price: 3000000,
      is_favorite_hotel: false,
    },
    {
      hotel_id: 9,
      hotel_name: "Khách sạn La Vague",
      hotel_address: "Số 8, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/9/1712891127616_Q9woy3sCMD_download5.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240412T030527Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=2cc11a6b1122f289daec9ace621f0eab7e1721b95ecc1cbbf5a994f699ae3b4d",
      min_room_price: 1480000,
      original_room_price: 1600000,
      is_favorite_hotel: false,
    },
    {
      hotel_id: 10,
      hotel_name: "The Empyrean Nha Trang",
      hotel_address: "2 , Nguyễn Thị Minh Khai, Thành Phố Nha Trang, Khánh Hòa",
      hotel_avatar:
        "http://localhost:9000/europetrip/hotels/10/1713772294727_9K84YkFRZM_room2.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240422%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240422T075134Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=8c0536fa4c5f6cb965ed5455559e8f7ab40efa84fbff790547e8169e2c64f269",
      min_room_price: 470000,
      original_room_price: 550000,
      is_favorite_hotel: false,
    },
  ],
};

export const amenitiesData = [
  {
    id: 1,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 2,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 3,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 4,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 5,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 6,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 7,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
  {
    id: 8,
    url: "https://storage.googleapis.com/tripi-assets/images/hotel/amenity/payment_jcb.png",
    name: "Wifi miễn phí",
  },
];

export const ratingData = [
  {
    id: 1,
    criteria: "Vị trí",
    rating: "8.4",
  },
  {
    id: 2,
    criteria: "Giá cả",
    rating: "8.6",
  },
  {
    id: 3,
    criteria: "Phục vụ",
    rating: "8.5",
  },
  {
    id: 4,
    criteria: "Vệ sinh",
    rating: "8.0",
  },
  {
    id: 5,
    criteria: "Tiện nghi",
    rating: "9.2",
  },
];

export const filterRoom = [
  "Không hút thuốc",
  "Có ăn sáng",
  "Lựa chọn trả tiền sau",
  "Hủy miễn phí",
  "Nhà bếp",
  "Giường đôi lớn",
  "Giường lớn",
  "Hai giường",
  "Hướng núi",
];

export const roomAmenities = [
  "Điều hòa nhiệt độ",
  "Khăn tắm",
  "Cửa sổ",
  "Không hút thuốc",
  "Đồ vệ sinh cá nhân miễn phí",
  "Tivi màn hình phẳng",
  "Phòng tắm riêng",
  "Bình nước nóng",
  "Wifi miễn phí",
  "Bàn làm việc",
  "Vòi hoa sen",
  "Tủ",
  "Trà, cà phê miễn phí",
  "Nước suối miễn phí",
  "Dọn phòng hàng ngày",
  "Ấm đun nước điện",
  "Kệ để hành lý",
  "Tủ quần áo",
  "Máy sấy tóc",
  "Giá treo quần áo",
];

export const roomBenefits = [
  "Hoàn huỷ một phần",
  "Giá đã bao gồm bữa sáng",
  "Chính sách đặt phòng & phụ thu",
  "Xác nhận trong 15 phút",
  "An tâm đặt phòng, Mytour hỗ trợ xuất hoá đơn nhanh chóng, tiết kiệm thời gian cho bạn.",
];

export const sortOptions = [
  {
    code: "newest",
    textDetail: "Mới nhất",
  },
  {
    code: "oldest",
    textDetail: "Cũ nhất",
  },
  {
    code: "lowest_rating",
    textDetail: "Điểm thấp nhất",
  },
  {
    code: "highest_rating",
    textDetail: "Điểm cao nhất",
  },
];

export const userInfo = {
  id: 2183063,
  email: "compareburden8600@gmail.com",
  ccEmail: null,
  emailInfo: "compareburden8600@gmail.com",
  phoneInfo: null,
  otpPhone: null,
  identifier: null,
  memberCard: {
    cardHolder: "JACKSON COOK",
    cardNumber: "3245977740560501",
    formattedCardNumber: "3245 9777 4056 0501",
    createdAt: 1576820350000,
    updatedAt: 1576820350000,
  },
  userSegment: null,
  preferredLanguage: {
    id: 1,
    code: "vi",
    name: "Vietnamese",
    flag: null,
    status: true,
    locale: "vi",
    banknetLocale: "vn",
  },
  country: null,
  userLangs: [],
  userDocuments: [],
  userPhoneNumbers: [],
  userBanks: [],
  userVatNumbers: null,
  name: "Jackson Cook",
  gender: "M",
  avatar:
    "https://lh3.googleusercontent.com/a/ACg8ocLjMs7A5JqUN3Kyj4MgVTZzrfc5j0CVottSZIIv_0lq9wrw8g=s96-c",
  profileVideo: null,
  companyName: null,
  signature: null,
  dateOfBirth: null,
  address: "",
  createdTime: 1713862072000,
  updatedTime: 1714375376000,
  joinTime: 1713862072000,
  caAccount: {
    id: 17,
    code: "MYTOUR",
    name: "Mytour",
    logo: "https://storage.googleapis.com/tripi-assets/mytour/icons/Mytour_logo_rebrand_2023_small.png",
    website: "https://mytour.vn",
    hotline: "1900 2083",
    supportEmail: "hotro@mytour.vn",
    phoneNumber: "1900 2083",
    fax: "091231",
    facebook: "facebook.com",
    twitter: "twitter.com",
    youtube: "youtube.com",
    fullName: "MyTour",
    address: "Tầng 11, Tòa nhà PeakView, 36 Hoàng Cầu, Đống Đa, Hà Nội",
    additionalInfo: "Ma so DN: 01812",
    shortName: "MyTour",
    activeSms: true,
    activeEmail: true,
    pointName: "Mytour Cash",
    ownPayment: false,
    refundPolicyLink: "https://hotro.tripi.vn/knowledgebase/quy-dinh-hoan-huy",
    reservationEmail: "reservations@tripi.vn",
    backupEmail: null,
    enableCreditPassword: false,
    rootUserId: null,
    enableCreditHolding: true,
    crmSupport: true,
    allowOpenSDKAuth: true,
    syncProviderBooking: false,
    enableCredit: true,
    enableAutoRefund: false,
    enableDeviceRestriction: false,
    applyPromoCodeForHoldingBooking: true,
    groupCode: "MYTOUR",
    promotionFraudCheck: true,
    maxHoldingBooking: 500,
    enableLoginNewDevice: false,
    smsCode: "MYTOUR-GLOBAL",
    creditHistoryCCEmail: null,
    cacheKey: "17",
    bankApp: false,
  },
  emailValidated: true,
  parentId: null,
  approveParent: false,
  isLmAccount: false,
  isTripiAdmin: false,
  isTripiSmgr: false,
  isTripiAccountant: false,
  isTripiSale: false,
  isTripiSupport: false,
  isLoyaltyAdmin: false,
  moduleBooker: null,
  isAgencyManager: false,
  agencyLevel: 0,
  countryName: null,
  score: 6,
  credit: 0,
  enableCredit: true,
  numPurchase: 0,
  lastPurchase: null,
  dayOfBirth: null,
  monthOfBirth: null,
  yearOfBirth: null,
  referralLog: null,
  isBlockBonusPoint: false,
  isActiveReferral: true,
  activeQrOfflineTopup: null,
  otherRoles: [],
  isCorporate: false,
  useCreditPassword: null,
  bookerRequest: null,
  userDetail: null,
  providerNotifications: [],
  currentAccessToken: null,
  supporter: null,
  roles: null,
  lastLoginDate: 1714398465000,
  active: true,
  providerNotification: null,
  hotelAdmin: false,
  accountant: false,
  marketing: false,
  tourAdmin: false,
  hotelProvider: false,
  hotelViewer: false,
  hotelRevenue: false,
  outsider: false,
  tourProvider: false,
  flightProvider: false,
  rootAccount: false,
  hotelEditor: false,
  supporters: [],
  nameNotNullOrEmpty: "Jackson Cook",
  loyalty: {
    id: 1398610,
    bonusPoint: 0,
    availablePoint: 0,
    remainingPoint: 0,
    rankProgress: 100,
    updateRankDate: 1714466639000,
    expiredPoint: 0,
    expiredDate: null,
    processingDate: null,
    createdAt: 1713862079000,
    updatedAt: 1714466639000,
  },
  markupForUser: null,
  userTitle: {
    name: "Thành viên mới",
    description:
      '<b>Quyền lợi thành viên</b><p><span style="color:#009933;">+</span> Đổi phần thưởng với số điểm ít hơn.</p><p><span style="color:#009933;">+</span> Ưu đãi kho hàng dành riêng cho Thành viên mới.</p>',
    card: {
      cardHolder: "JACKSON COOK",
      cardNumber: "3245977740560501",
      formattedCardNumber: "3245 9777 4056 0501",
      createdAt: 1576820350000,
      updatedAt: 1576820350000,
    },
    icon: "https://gcs.tripi.vn/tripi-assets/images/Loyalty/rank/newbie.png",
    lockIcon:
      "https://gcs.tripi.vn/tripi-assets/images/Loyalty/Icon/B%20-%20Newbie.png",
    no: 0,
    rankPoint: 0,
    color: "#009688",
    cardBackground:
      "https://gcs.tripi.vn/tripi-assets/dinogo/images/member_cards/dinogo-card-thanh-vien.png",
    popupIcon:
      "https://gcs.tripi.vn/tripi-assets/dinogo/images/loyalty/award-badge-member.png",
  },
  loyaltyInfo: {
    rewardNum: 6,
  },
  baseInfoStr:
    "Id: 2183063\nTên: Jackson Cook\nEmail: compareburden8600@gmail.com\nSố điện thoại: null",
  providerNotificationList: [],
  userInfo: {
    id: 2183063,
    name: "Jackson Cook",
    credit: 0,
    enableCredit: true,
    availableCredit: 0,
    totalHoldingCredit: 0,
  },
  businessInfo: [],
  loginType: "google",
  availableCredit: 0,
  totalHoldingCredit: 0,
};

export const searchResult = [
  {
    hotel_id: 38527,
    hotel_name: "Khách sạn La Vague",
    hotel_address: "Số 8, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 48801,
    hotel_name: "Khách sạn Grand Gosia Nha Trang",
    hotel_address:
      "10-12 Trần Phú, Vĩnh Nguyên, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://storage.googleapis.com/hms_prod/photo/thumb/1617092342927GY/144944532.png",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 38483,
    hotel_name: "Khách sạn Sea Pearl Nha Trang",
    hotel_address: "98a, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 48130,
    hotel_name: "The Empyrean Nha Trang",
    hotel_address: "2 , Nguyễn Thị Minh Khai, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 38437,
    hotel_name: "Khách sạn Ibis Styles Nha Trang",
    hotel_address: "86, Hùng Vương, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/img/467043orJ/z4260616666973_ae897d5bc64a75a0a960e005004c5497.jpg",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 38380,
    hotel_name: "Khách sạn Boton Blue & Spa Nha Trang",
    hotel_address:
      "Phạm Văn Đồng, Phường Vĩnh Hòa, Phạm Văn Đồng, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 38406,
    hotel_name: "TUI BLUE - Khách sạn TUI BLUE Nha Trang",
    hotel_address: "18, Trần Hưng Đạo, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 38664,
    hotel_name: "Khách Sạn Mường Thanh Luxury Nha Trang",
    hotel_address: "60, Trần Phú, Lộc Thọ, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1620472922630mr/293542180_result.jpg",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 9723,
    hotel_name: "Khách Sạn Mường Thanh Grand Nha Trang",
    hotel_address: "6 , Dương Hiến Quyền, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616860211117eh/283800904.png",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 45768,
    hotel_name: "Khách sạn Merperle Beach Nha Trang",
    hotel_address: "88a, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FDETKKSYJY7_%2Ftmp%2Fplaytemp7486223076244920531%2FmultipartBody4363323379706674084asTemporaryFile?generation=1592549175846288&alt=media",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 38470,
    hotel_name: "Khách Sạn Majestic Premium Nha Trang",
    hotel_address: "96b5/4 , Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1617199586684xK/152261603.jpg",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 512,
    hotel_name: "Khách sạn Sheraton Nha Trang",
    hotel_address: "26-28, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://www.googleapis.com/download/storage/v1/b/hotel_image/o/logo%2F4%2F210187.jpg?generation=1563771731644355&alt=media",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 553,
    hotel_name: "Khách Sạn Novotel Nha Trang",
    hotel_address: "50, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FXMS2N0BE6X_%2Ftmp%2Fplaytemp4401775770632333474%2FmultipartBody6774088289307231415asTemporaryFile?generation=1586178743406910&alt=media",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 8496,
    hotel_name: "Khách sạn StarCity Nha Trang",
    hotel_address: "72-74 , Trần Phú, Lộc Thọ, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616818433346JL/out.png",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 38396,
    hotel_name: "Vinpearl  Beachfront Nha Trang",
    hotel_address:
      "78-80 Trần Phú, Phường Lộc Thọ, Trần Phú, Lộc Thọ, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616841710477jp/dai-dien.png",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
  {
    hotel_id: 2048,
    hotel_name: "Champa Island Nha Trang - Resort Hotel & Spa   ",
    hotel_address: "304 , 2/4, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/img/469422dbJ/z4420199007786_a80da51a029391ded0f8199ec2230a6a.jpg",
    min_room_price: 900000,
    original_room_price: 1000000,
  },
];

export const favoriteHotels = [
  {
    hotel_id: 38527,
    hotel_name: "Khách sạn La Vague",
    hotel_address: "Số 8, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616771153173ME/outside.png",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 48801,
    hotel_name: "Khách sạn Grand Gosia Nha Trang",
    hotel_address:
      "10-12 Trần Phú, Vĩnh Nguyên, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://storage.googleapis.com/hms_prod/photo/thumb/1617092342927GY/144944532.png",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 38483,
    hotel_name: "Khách sạn Sea Pearl Nha Trang",
    hotel_address: "98a, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1617174369612dF/172059893.jpg",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 48130,
    hotel_name: "The Empyrean Nha Trang",
    hotel_address: "2 , Nguyễn Thị Minh Khai, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616819671281ZO/40510723.png",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 38437,
    hotel_name: "Khách sạn Ibis Styles Nha Trang",
    hotel_address: "86, Hùng Vương, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/img/467043orJ/z4260616666973_ae897d5bc64a75a0a960e005004c5497.jpg",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 38380,
    hotel_name: "Khách sạn Boton Blue & Spa Nha Trang",
    hotel_address:
      "Phạm Văn Đồng, Phường Vĩnh Hòa, Phạm Văn Đồng, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/2685xI/ecea6c41b2d197bd06460bee7ab542b0.jpg",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 38406,
    hotel_name: "TUI BLUE - Khách sạn TUI BLUE Nha Trang",
    hotel_address: "18, Trần Hưng Đạo, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/img/470238wvF/dji_0056.jpg",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 38664,
    hotel_name: "Khách Sạn Mường Thanh Luxury Nha Trang",
    hotel_address: "60, Trần Phú, Lộc Thọ, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1620472922630mr/293542180_result.jpg",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 9723,
    hotel_name: "Khách Sạn Mường Thanh Grand Nha Trang",
    hotel_address: "6 , Dương Hiến Quyền, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616860211117eh/283800904.png",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 45768,
    hotel_name: "Khách sạn Merperle Beach Nha Trang",
    hotel_address: "88a, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FDETKKSYJY7_%2Ftmp%2Fplaytemp7486223076244920531%2FmultipartBody4363323379706674084asTemporaryFile?generation=1592549175846288&alt=media",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 38470,
    hotel_name: "Khách Sạn Majestic Premium Nha Trang",
    hotel_address: "96b5/4 , Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1617199586684xK/152261603.jpg",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 512,
    hotel_name: "Khách sạn Sheraton Nha Trang",
    hotel_address: "26-28, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://www.googleapis.com/download/storage/v1/b/hotel_image/o/logo%2F4%2F210187.jpg?generation=1563771731644355&alt=media",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 553,
    hotel_name: "Khách Sạn Novotel Nha Trang",
    hotel_address: "50, Trần Phú, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FXMS2N0BE6X_%2Ftmp%2Fplaytemp4401775770632333474%2FmultipartBody6774088289307231415asTemporaryFile?generation=1586178743406910&alt=media",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 8496,
    hotel_name: "Khách sạn StarCity Nha Trang",
    hotel_address: "72-74 , Trần Phú, Lộc Thọ, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616818433346JL/out.png",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 38396,
    hotel_name: "Vinpearl  Beachfront Nha Trang",
    hotel_address:
      "78-80 Trần Phú, Phường Lộc Thọ, Trần Phú, Lộc Thọ, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/thumb/1616841710477jp/dai-dien.png",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
  {
    hotel_id: 2048,
    hotel_name: "Champa Island Nha Trang - Resort Hotel & Spa   ",
    hotel_address: "304 , 2/4, Thành Phố Nha Trang, Khánh Hòa",
    hotel_avatar:
      "https://gcs.tripi.vn/hms_prod/photo/img/469422dbJ/z4420199007786_a80da51a029391ded0f8199ec2230a6a.jpg",
    hotel_rating: 8.8,
    is_favorite_hotel: true,
  },
];

export const myBookings = [
  {
    id: 2535276,
    orderCode: "H2535276",
    orderToken: "46bcf29a-2aa9-45c5-b159-419486b5dcf1",
    hotel: {
      id: 955,
      name: "Khách Sạn Imperial Vũng Tàu",
      starNumber: 5,
      slug: "khach-san-imperial-vung-tau-h955",
      category: {
        id: 1,
        name: "Khách sạn",
        code: "hotel",
      },
      categoryGroup: {
        id: 1,
        name: "Khách sạn",
        code: "hotel",
      },
      address: {
        streetId: 23279,
        streetName: "Thuỳ Vân",
        districtId: 686,
        districtName: "Thành Phố Vũng Tàu",
        provinceId: 15,
        provinceName: "Bà Rịa - Vũng Tàu",
        countryId: 1,
        country: "Việt Nam",
        coordinate: {
          latitude: 10.343982244710237,
          longitude: 107.0949786901474,
        },
        address: "159, Thuỳ Vân, Thành Phố Vũng Tàu, Bà Rịa Vũng Tàu, Việt Nam",
        interestingPlace: null,
        staticMap: null,
      },
      checkInTime: "15:00",
      checkOutTime: "12:00",
      isFavoriteHotel: false,
      thumbnail: {
        id: null,
        desc: null,
        src: "https://img.tripi.vn/cdn-cgi/image/width=320/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
        photoType: null,
        image: {
          origin:
            "https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
          small:
            "https://img.tripi.vn/cdn-cgi/image/width=320/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
          medium:
            "https://img.tripi.vn/cdn-cgi/image/width=640/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
          large:
            "https://img.tripi.vn/cdn-cgi/image/width=1280/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
        },
      },
      videoUrl: null,
      rating: {
        hotel: {
          rating: 4.4,
          locationRating: 4.4,
          priceRating: 4.4,
          serviceRating: 4.4,
          cleanlinessRating: 4.4,
          convenientRating: 4.4,
          count: 1348,
        },
        tripadvisor: {
          rating: 4.4,
          locationRating: 0,
          priceRating: 0,
          serviceRating: 0,
          cleanlinessRating: 0,
          convenientRating: 0,
          count: 0,
          reviewLink: null,
        },
      },
      lastBookedTime: 1714648296000,
      myPlus: false,
      descriptions:
        "<p>Tọa lạc tại vị trí đắc địa ở thành phố Vũng Tàu, khách sạn Imperial với tiêu chuẩn 5 sao nằm ở vị trí ven biển. Tại đây, quý khách dễ dàng di chuyển đến các điểm du lịch nỗi tiếng gần đó như: Bãi Sau, Bãi Trước, Tượng Chúa Kito, Mũi Nghinh Phong, Đồi Con Heo.... Sân bay gần nhất là sân bay Quốc Tế&nbsp;Tân Sơn Nhất, cách khách sạn 100&nbsp;km.</p>\n<p>Khách sạn Imperial có nhà hàng trong khuôn viên phục vụ bữa sáng và nhu cầu ẩm thực của quý khách. Khách sạn&nbsp;gồm 3 nhà hàng và 3 bar/ lounge: Dining Room, Asia Selection, ShiFu Chinnese Bistro, Lobby Lounge, The Imperial Theatre, La Sirena Bar Grill.</p>\n<p>Khách sạn có 2 hồ bơi, 1 hồ bơi bên khu khách sạn cho khách muốn di chuyển gần, hồ bơi thứ 2 là bên đường ngay bãi biển, có 1 cầu vượt để qua đường sử dụng hồ bơi phía bên biển, tại đây khách có thể tắm hồ bơi và tắm biển, resort có set up ghế dù cho khách tắm biển. Khu hồ bơi khách sạn có hỗ trợ hồ bơi dành cho trẻ em với mức nước khá thấp.</p>\n<p>Từ khi xây dựng cho đến nay, khách sạn Imperial&nbsp;liên tục có những thay đổi, làm mới dịch vụ để trở thành một nơi lý tưởng dành cho khách du lịch, thương nhân và cả những người muốn đến để thưởng thức ẩm thực, hội họp hay tổ chức tiệc. Bên cạnh đó mang lại cho du khách sự tận hưởng các tiện ích hàng đầu cũng như ăn uống, vui chơi giải trí như:</p>\n<ul>\n  <li>Wi-Fi miễn phí</li>\n  <li>Dọn phòng hằng ngày</li>\n  <li>Bể bơi</li>\n  <li>Phòng tập Gym</li>\n  <li>Nhà hàng</li>\n  <li>Lễ tân 24/7</li>\n</ul>\n<p>Khách sạn Imperial Vũng Tàu&nbsp;gồm 144 phòng khách sạn và khoảng 206 phòng căn hộ, được trang trí bằng giấy dán tường viền gỗ rất trang nhã, điểm thêm những bức tranh nổi tiếng thời nữ hoàng Victoria.</p>\n<p><br></p>\n<p><strong>Khu khách sạn:</strong> gồm 22 loại phòng được trang trí đặc sắc khác nhau bắt đầu từ Deluxe đến IMPERIAL Suite, diện tích từ 40m² - 265m², hướng nhìn ra bãi biển tuyệt đẹp hoặc khu vườn Thượng Uyển tựa mình vào sườn núi.<br>\n<br>\n<strong>Phòng Deluxe:</strong> có diện tích từ 37 - 40 m2, hướng phố hoặc hồ bơi, một số phòng không có ban công, có thể kê thêm 1 giường phụ, bồn tắm nằm.</p>\n<p><em>+ Deluxe Double: phòng dành cho 2 khách với 1 giường đôi 1m8</em></p>\n<p><em>+ Deluxe Twin: phòng dành cho 2 khách với 02 giường đơn 1m2</em><br>\n</p>\n<p><strong>Premium Deluxe:</strong> có diện tích từ 37 - 40 m2, thiết kế theo phong cách cổ điển Châu Âu và một số phòng có tầm nhìn hướng biển, phòng có 1 giường đôi dành cho 2 khách, có thể kê thêm 1 giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Grand Triple:</strong> phòng có diện tích 45 m2, bao gồm 1 giường đôi lớn&nbsp;và 1 giường đơn, là một lựa chọn hoàn hảo cho gia đình, có hướng nhìn ra biển hoặc thành phố, không thể kê thêm giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Victorian Suite:</strong> diện tích phòng khoảng 55 - 60m2, có 1 phòng ngủ, ban công nhìn ra hướng biển (01 số phòng không có ban công hướng biển), có 1 giường đôi lớn, có phòng tiếp khách, không thể kê thêm giường phụ, bồn tắm nằm.<br>\n<br>\n<strong>*Khu căn hộ:</strong> với hơn 206 phòng thẳng ra biển của Bãi sau Vũng Tàu, các phòng đều có trang bị bếp và phòng ăn riêng mang lại cho du khách cảm giác ấm cúng và hạnh phúc bên gia đình.<br>\n</p>\n<p><strong>Deluxe:</strong> có diện tích từ 45 - 50 m2, hướng phố hoặc một phần hướng biển, có thể kê thêm 1 giường phụ, bồn tắm nằm.</p>\n<p><em>+ Deluxe Double: phòng dành cho 2 khách với 1 giường đôi 1m8</em></p>\n<p><em>+ Deluxe Twin: phòng dành cho 2 khách với 02 giường đơn 1m</em><br>\n</p>\n<p><strong>Premium Deluxe:</strong> có diện tích khoảng 55 m2, hướng thành phố, biển hạn chế, phòng có 1 giường đôi dành cho 2 khách, có thể kê thêm 1 giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Grand Suite:</strong> phòng có diện tích khoảng 60 m2, với hướng thành phố, biển hạn chế, phòng có 1 giường đôi dành cho 2 khách, có thể kê thêm 1 giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Family Suite:</strong> phòng dành 4 khách, diện tích khoảng 100 m2, gồm 1 giường đôi lớn&nbsp;và 2 giường ngủ đơn, hướng hồ bơi, thành phố, biển hạn chế, có thể kê thêm tối đa 2 giường phụ, bồn tắm nằm.&nbsp;</p>",
      policies: [],
      distanceToCityCenter: 1.5,
      distanceToDistrictCenter: 8.613095575270178,
      distanceToAirport: 120,
      numFloors: 18,
      buildYear: 2009,
      numRestaurants: 3,
      numBars: 3,
      numRooms: 365,
      images: [],
      groupAmenities: null,
      chain: null,
      location: null,
      tags: [],
    },
    checkIn: "03-05-2024",
    checkOut: "08-05-2024",
    numAdult: 8,
    numChildren: 3,
    numRooms: 4,
    childrenAges: [10, 5, 4],
    userId: 2183063,
    freeBreakfast: true,
    freeCancellation: false,
    bookingDate: "2024-05-02 11:17:01",
    expiredTime: "2024-05-02 23:59:00",
    expiredTimestamp: 1714669140000,
    changeStayDateSchedule: null,
    paymentStatus: "waiting",
    partnerBookingCode: "MT1040307213",
    checkinCode: "MT1040307213",
    bookingStatus: "waiting",
    processFlow: null,
    reviewHashKey:
      "IXYc9arz6h+qQyl2dcYZaTvLKjpnRCh5NhJefoGicdP1T5QuomvDq3XupHGubdlZ1H2lelzed0YjkdnVDbvFLj4Abo9nG10X9aiuj3f2dJ2QG1Arci0i8w==",
    basePrice: 2978974,
    basePriceFormatted: null,
    priceWithoutBookerMarkup: 3294000,
    priceWithoutBookerMarkupFormatted: "3.294.000 đ",
    price: 3294000,
    priceFormatted: "3.294.000 đ",
    totalRoomPrice: 65880000,
    totalRoomPriceFormatted: "65.880.000 đ",
    promotionCode: "IMPE400",
    discount: 8000000,
    discountFormatted: "8.000.000 đ",
    bonusPoint: 0,
    paidPoint: 0,
    pointAmount: 0,
    pointAmountFormatted: "0 đ",
    finalPrice: 57880000,
    finalPriceFormatted: "57.880.000 đ",
    customerPrice: 65880000,
    paymentMethodFee: 0,
    totalPrice: 65880000,
    totalPriceFormatted: "65.880.000 đ",
    paymentMethod: "Chưa thanh toán",
    paymentMethodId: 99,
    paymentMethodCode: "NPM",
    includedVAT: true,
    customer: {
      name: "Jackson Cook",
      phone: "+844535345353",
      email: "compareburden8600@gmail.com",
      address: "",
    },
    invoiceInfo: {
      invoiceType: "not_marketplace",
      invoiceDescription: null,
      invoiceInfo: "Quý khách vui lòng liên hệ Mytour CSKH để xuất hoá đơn.",
      customerName: null,
      companyAddress: null,
      companyName: null,
      taxNumber: null,
      recipientAddress: null,
      recipientEmail: null,
      recipientName: null,
      recipientPhone: null,
      note: null,
      resolved: null,
    },
    purchaseType: "personal",
    providerConfirmStatus: null,
    canReview: false,
    roomBookings: [
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [10],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 1080000,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072131ZM",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [5],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072132JE",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [4],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072133HM",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 0,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072134HY",
        nightlyPrices: null,
      },
    ],
    agencyId: 27,
    providerStatus: "fail",
    repay: true,
    cancelPolicies: [
      "Nếu hủy phòng trước 15:00 ngày 03/05, chúng tôi sẽ thu 65.760.000 đ phí hủy phòng.",
      "Nếu hủy phòng từ 15:00 ngày 03/05, chúng tôi sẽ thu 65.875.000 đ phí hủy phòng.",
    ],
    bookingAdditions: null,
    allowCancelInApp: false,
    currency: {
      id: 1,
      code: "VND",
      symbol: "đ",
      rate: 1,
    },
    reservationCodes: [],
    hashBookingId: "8MVV2udwiHUM3j8XwFx4Kw==",
    refundHoldingMoneyStatus: null,
    lang: "vi",
    affUserId: null,
    affiliateId: null,
  },
  {
    id: 2535277,
    orderCode: "H2535276",
    orderToken: "46bcf29a-2aa9-45c5-b159-419486b5dcf1",
    hotel: {
      id: 955,
      name: "Khách Sạn Imperial Vũng Tàu",
      starNumber: 5,
      slug: "khach-san-imperial-vung-tau-h955",
      category: {
        id: 1,
        name: "Khách sạn",
        code: "hotel",
      },
      categoryGroup: {
        id: 1,
        name: "Khách sạn",
        code: "hotel",
      },
      address: {
        streetId: 23279,
        streetName: "Thuỳ Vân",
        districtId: 686,
        districtName: "Thành Phố Vũng Tàu",
        provinceId: 15,
        provinceName: "Bà Rịa - Vũng Tàu",
        countryId: 1,
        country: "Việt Nam",
        coordinate: {
          latitude: 10.343982244710237,
          longitude: 107.0949786901474,
        },
        address: "159, Thuỳ Vân, Thành Phố Vũng Tàu, Bà Rịa Vũng Tàu, Việt Nam",
        interestingPlace: null,
        staticMap: null,
      },
      checkInTime: "15:00",
      checkOutTime: "12:00",
      isFavoriteHotel: false,
      thumbnail: {
        id: null,
        desc: null,
        src: "https://img.tripi.vn/cdn-cgi/image/width=320/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
        photoType: null,
        image: {
          origin:
            "https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
          small:
            "https://img.tripi.vn/cdn-cgi/image/width=320/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
          medium:
            "https://img.tripi.vn/cdn-cgi/image/width=640/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
          large:
            "https://img.tripi.vn/cdn-cgi/image/width=1280/https://googleapis.tripi.vn/download/storage/v1/b/tourcdn/o/photos%2FBZ1O6VKR21_%2Ftmp%2Fplaytemp8992226862162980543%2FmultipartBody8889052234719766714asTemporaryFile?generation=1595488423270831&alt=media",
        },
      },
      videoUrl: null,
      rating: {
        hotel: {
          rating: 4.4,
          locationRating: 4.4,
          priceRating: 4.4,
          serviceRating: 4.4,
          cleanlinessRating: 4.4,
          convenientRating: 4.4,
          count: 1348,
        },
        tripadvisor: {
          rating: 4.4,
          locationRating: 0,
          priceRating: 0,
          serviceRating: 0,
          cleanlinessRating: 0,
          convenientRating: 0,
          count: 0,
          reviewLink: null,
        },
      },
      lastBookedTime: 1714648296000,
      myPlus: false,
      descriptions:
        "<p>Tọa lạc tại vị trí đắc địa ở thành phố Vũng Tàu, khách sạn Imperial với tiêu chuẩn 5 sao nằm ở vị trí ven biển. Tại đây, quý khách dễ dàng di chuyển đến các điểm du lịch nỗi tiếng gần đó như: Bãi Sau, Bãi Trước, Tượng Chúa Kito, Mũi Nghinh Phong, Đồi Con Heo.... Sân bay gần nhất là sân bay Quốc Tế&nbsp;Tân Sơn Nhất, cách khách sạn 100&nbsp;km.</p>\n<p>Khách sạn Imperial có nhà hàng trong khuôn viên phục vụ bữa sáng và nhu cầu ẩm thực của quý khách. Khách sạn&nbsp;gồm 3 nhà hàng và 3 bar/ lounge: Dining Room, Asia Selection, ShiFu Chinnese Bistro, Lobby Lounge, The Imperial Theatre, La Sirena Bar Grill.</p>\n<p>Khách sạn có 2 hồ bơi, 1 hồ bơi bên khu khách sạn cho khách muốn di chuyển gần, hồ bơi thứ 2 là bên đường ngay bãi biển, có 1 cầu vượt để qua đường sử dụng hồ bơi phía bên biển, tại đây khách có thể tắm hồ bơi và tắm biển, resort có set up ghế dù cho khách tắm biển. Khu hồ bơi khách sạn có hỗ trợ hồ bơi dành cho trẻ em với mức nước khá thấp.</p>\n<p>Từ khi xây dựng cho đến nay, khách sạn Imperial&nbsp;liên tục có những thay đổi, làm mới dịch vụ để trở thành một nơi lý tưởng dành cho khách du lịch, thương nhân và cả những người muốn đến để thưởng thức ẩm thực, hội họp hay tổ chức tiệc. Bên cạnh đó mang lại cho du khách sự tận hưởng các tiện ích hàng đầu cũng như ăn uống, vui chơi giải trí như:</p>\n<ul>\n  <li>Wi-Fi miễn phí</li>\n  <li>Dọn phòng hằng ngày</li>\n  <li>Bể bơi</li>\n  <li>Phòng tập Gym</li>\n  <li>Nhà hàng</li>\n  <li>Lễ tân 24/7</li>\n</ul>\n<p>Khách sạn Imperial Vũng Tàu&nbsp;gồm 144 phòng khách sạn và khoảng 206 phòng căn hộ, được trang trí bằng giấy dán tường viền gỗ rất trang nhã, điểm thêm những bức tranh nổi tiếng thời nữ hoàng Victoria.</p>\n<p><br></p>\n<p><strong>Khu khách sạn:</strong> gồm 22 loại phòng được trang trí đặc sắc khác nhau bắt đầu từ Deluxe đến IMPERIAL Suite, diện tích từ 40m² - 265m², hướng nhìn ra bãi biển tuyệt đẹp hoặc khu vườn Thượng Uyển tựa mình vào sườn núi.<br>\n<br>\n<strong>Phòng Deluxe:</strong> có diện tích từ 37 - 40 m2, hướng phố hoặc hồ bơi, một số phòng không có ban công, có thể kê thêm 1 giường phụ, bồn tắm nằm.</p>\n<p><em>+ Deluxe Double: phòng dành cho 2 khách với 1 giường đôi 1m8</em></p>\n<p><em>+ Deluxe Twin: phòng dành cho 2 khách với 02 giường đơn 1m2</em><br>\n</p>\n<p><strong>Premium Deluxe:</strong> có diện tích từ 37 - 40 m2, thiết kế theo phong cách cổ điển Châu Âu và một số phòng có tầm nhìn hướng biển, phòng có 1 giường đôi dành cho 2 khách, có thể kê thêm 1 giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Grand Triple:</strong> phòng có diện tích 45 m2, bao gồm 1 giường đôi lớn&nbsp;và 1 giường đơn, là một lựa chọn hoàn hảo cho gia đình, có hướng nhìn ra biển hoặc thành phố, không thể kê thêm giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Victorian Suite:</strong> diện tích phòng khoảng 55 - 60m2, có 1 phòng ngủ, ban công nhìn ra hướng biển (01 số phòng không có ban công hướng biển), có 1 giường đôi lớn, có phòng tiếp khách, không thể kê thêm giường phụ, bồn tắm nằm.<br>\n<br>\n<strong>*Khu căn hộ:</strong> với hơn 206 phòng thẳng ra biển của Bãi sau Vũng Tàu, các phòng đều có trang bị bếp và phòng ăn riêng mang lại cho du khách cảm giác ấm cúng và hạnh phúc bên gia đình.<br>\n</p>\n<p><strong>Deluxe:</strong> có diện tích từ 45 - 50 m2, hướng phố hoặc một phần hướng biển, có thể kê thêm 1 giường phụ, bồn tắm nằm.</p>\n<p><em>+ Deluxe Double: phòng dành cho 2 khách với 1 giường đôi 1m8</em></p>\n<p><em>+ Deluxe Twin: phòng dành cho 2 khách với 02 giường đơn 1m</em><br>\n</p>\n<p><strong>Premium Deluxe:</strong> có diện tích khoảng 55 m2, hướng thành phố, biển hạn chế, phòng có 1 giường đôi dành cho 2 khách, có thể kê thêm 1 giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Grand Suite:</strong> phòng có diện tích khoảng 60 m2, với hướng thành phố, biển hạn chế, phòng có 1 giường đôi dành cho 2 khách, có thể kê thêm 1 giường phụ, bồn tắm nằm.<br>\n</p>\n<p><strong>Family Suite:</strong> phòng dành 4 khách, diện tích khoảng 100 m2, gồm 1 giường đôi lớn&nbsp;và 2 giường ngủ đơn, hướng hồ bơi, thành phố, biển hạn chế, có thể kê thêm tối đa 2 giường phụ, bồn tắm nằm.&nbsp;</p>",
      policies: [],
      distanceToCityCenter: 1.5,
      distanceToDistrictCenter: 8.613095575270178,
      distanceToAirport: 120,
      numFloors: 18,
      buildYear: 2009,
      numRestaurants: 3,
      numBars: 3,
      numRooms: 365,
      images: [],
      groupAmenities: null,
      chain: null,
      location: null,
      tags: [],
    },
    checkIn: "03-05-2024",
    checkOut: "08-05-2024",
    numAdult: 8,
    numChildren: 3,
    numRooms: 4,
    childrenAges: [10, 5, 4],
    userId: 2183063,
    freeBreakfast: true,
    freeCancellation: false,
    bookingDate: "2024-05-02 11:17:01",
    expiredTime: "2024-05-02 23:59:00",
    expiredTimestamp: 1714669140000,
    changeStayDateSchedule: null,
    paymentStatus: "waiting",
    partnerBookingCode: "MT1040307213",
    checkinCode: "MT1040307213",
    bookingStatus: "waiting",
    processFlow: null,
    reviewHashKey:
      "IXYc9arz6h+qQyl2dcYZaTvLKjpnRCh5NhJefoGicdP1T5QuomvDq3XupHGubdlZ1H2lelzed0YjkdnVDbvFLj4Abo9nG10X9aiuj3f2dJ2QG1Arci0i8w==",
    basePrice: 2978974,
    basePriceFormatted: null,
    priceWithoutBookerMarkup: 3294000,
    priceWithoutBookerMarkupFormatted: "3.294.000 đ",
    price: 3294000,
    priceFormatted: "3.294.000 đ",
    totalRoomPrice: 65880000,
    totalRoomPriceFormatted: "65.880.000 đ",
    promotionCode: "IMPE400",
    discount: 8000000,
    discountFormatted: "8.000.000 đ",
    bonusPoint: 0,
    paidPoint: 0,
    pointAmount: 0,
    pointAmountFormatted: "0 đ",
    finalPrice: 57880000,
    finalPriceFormatted: "57.880.000 đ",
    customerPrice: 65880000,
    paymentMethodFee: 0,
    totalPrice: 65880000,
    totalPriceFormatted: "65.880.000 đ",
    paymentMethod: "Chưa thanh toán",
    paymentMethodId: 99,
    paymentMethodCode: "NPM",
    includedVAT: true,
    customer: {
      name: "Jackson Cook",
      phone: "+844535345353",
      email: "compareburden8600@gmail.com",
      address: "",
    },
    invoiceInfo: {
      invoiceType: "not_marketplace",
      invoiceDescription: null,
      invoiceInfo: "Quý khách vui lòng liên hệ Mytour CSKH để xuất hoá đơn.",
      customerName: null,
      companyAddress: null,
      companyName: null,
      taxNumber: null,
      recipientAddress: null,
      recipientEmail: null,
      recipientName: null,
      recipientPhone: null,
      note: null,
      resolved: null,
    },
    purchaseType: "personal",
    providerConfirmStatus: null,
    canReview: false,
    roomBookings: [
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [10],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 1080000,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072131ZM",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [5],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072132JE",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [4],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072133HM",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 0,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072134HY",
        nightlyPrices: null,
      },
    ],
    agencyId: 27,
    providerStatus: "fail",
    repay: true,
    cancelPolicies: [
      "Nếu hủy phòng trước 15:00 ngày 03/05, chúng tôi sẽ thu 65.760.000 đ phí hủy phòng.",
      "Nếu hủy phòng từ 15:00 ngày 03/05, chúng tôi sẽ thu 65.875.000 đ phí hủy phòng.",
    ],
    bookingAdditions: null,
    allowCancelInApp: false,
    currency: {
      id: 1,
      code: "VND",
      symbol: "đ",
      rate: 1,
    },
    reservationCodes: [],
    hashBookingId: "8MVV2udwiHUM3j8XwFx4Kw==",
    refundHoldingMoneyStatus: null,
    lang: "vi",
    affUserId: null,
    affiliateId: null,
  },
];
